spring.application.name=CourseRegistration
spring.datasource.url=jdbc:mysql://localhost:3306/kt?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=17092004
spring.jpa.hibernate.ddl-auto=update